package com.Trang.webyte.mapper;

import com.Trang.webyte.model.Account;
import com.Trang.webyte.model.AccountExample;
import com.Trang.webyte.model.AccountKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	long countByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	int deleteByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	int deleteByPrimaryKey(AccountKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	int insert(Account row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	int insertSelective(Account row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	List<Account> selectByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	Account selectByPrimaryKey(AccountKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Account row, @Param("example") AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	int updateByExample(@Param("row") Account row, @Param("example") AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	int updateByPrimaryKeySelective(Account row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	int updateByPrimaryKey(Account row);

}