package com.Trang.webyte.mapper;

import com.Trang.webyte.model.Account;
import com.Trang.webyte.model.AccountExample;
import com.Trang.webyte.model.AccountKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	long countByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int deleteByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int deleteByPrimaryKey(AccountKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int insert(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int insertSelective(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	List<Account> selectByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	Account selectByPrimaryKey(AccountKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int updateByPrimaryKeySelective(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int updateByPrimaryKey(Account record);

}