package com.Trang.webyte.mapper;

import com.Trang.webyte.model.admin;
import com.Trang.webyte.model.adminExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface adminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	long countByExample(adminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int deleteByExample(adminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int insert(admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int insertSelective(admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	List<admin> selectByExample(adminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	admin selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int updateByExampleSelective(@Param("record") admin record, @Param("example") adminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int updateByExample(@Param("record") admin record, @Param("example") adminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int updateByPrimaryKeySelective(admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	int updateByPrimaryKey(admin record);
}