package com.Trang.webyte.mapper;

import com.Trang.webyte.model.Appointment_Schedule;
import com.Trang.webyte.model.Appointment_ScheduleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface Appointment_ScheduleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_schedule
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	long countByExample(Appointment_ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_schedule
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	int deleteByExample(Appointment_ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_schedule
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	int deleteByPrimaryKey(Integer idappointmentSchedule);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_schedule
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	int insert(Appointment_Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_schedule
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	int insertSelective(Appointment_Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_schedule
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	List<Appointment_Schedule> selectByExample(Appointment_ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_schedule
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	Appointment_Schedule selectByPrimaryKey(Integer idappointmentSchedule);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_schedule
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	int updateByExampleSelective(@Param("record") Appointment_Schedule record,
			@Param("example") Appointment_ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_schedule
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	int updateByExample(@Param("record") Appointment_Schedule record,
			@Param("example") Appointment_ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_schedule
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	int updateByPrimaryKeySelective(Appointment_Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_schedule
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	int updateByPrimaryKey(Appointment_Schedule record);
}