package com.Trang.webyte.mapper;

import com.Trang.webyte.model.Dept;
import com.Trang.webyte.model.DeptExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DeptMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	long countByExample(DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int deleteByExample(DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int deleteByPrimaryKey(Integer deptid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int insert(Dept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int insertSelective(Dept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	List<Dept> selectByExample(DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	Dept selectByPrimaryKey(Integer deptid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByPrimaryKeySelective(Dept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByPrimaryKey(Dept record);
}