package com.Trang.webyte.mapper;

import com.Trang.webyte.DTO.DoctorDTO;
import com.Trang.webyte.model.Doctor;
import com.Trang.webyte.model.DoctorExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DoctorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	long countByExample(DoctorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int deleteByExample(DoctorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int deleteByPrimaryKey(Integer doctorid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int insert(Doctor row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int insertSelective(Doctor row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	List<Doctor> selectByExample(DoctorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	Doctor selectByPrimaryKey(Integer doctorid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Doctor row, @Param("example") DoctorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int updateByExample(@Param("row") Doctor row, @Param("example") DoctorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int updateByPrimaryKeySelective(Doctor row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int updateByPrimaryKey(Doctor row);
	List<Map<String,Object>> selectAllDoctor();
}
