package com.Trang.webyte.mapper;
import com.Trang.webyte.model.Doctor;
import com.Trang.webyte.model.DoctorExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import javax.print.Doc;

@Mapper
public interface DoctorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	long countByExample(DoctorExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int deleteByExample(DoctorExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int deleteByPrimaryKey(Integer doctorid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int insert(Doctor record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int insertSelective(Doctor record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	List<Doctor> selectByExample(DoctorExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	Doctor selectByPrimaryKey(Integer doctorid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByExampleSelective(@Param("record") Doctor record, @Param("example") DoctorExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByExample(@Param("record") Doctor record, @Param("example") DoctorExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByPrimaryKeySelective(Doctor record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByPrimaryKey(Doctor record);
	List<Map<String,Object>> selectAllDoctor();
	List<Map<String,Object>> getListDoctorByDept(Map<String,Object> resul);
}
