package com.Trang.webyte.mapper;

import com.Trang.webyte.model.DutySchedule;
import com.Trang.webyte.model.DutyScheduleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DutyScheduleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dutyschedule
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	long countByExample(DutyScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dutyschedule
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int deleteByExample(DutyScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dutyschedule
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int deleteByPrimaryKey(Integer dutyscheduleid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dutyschedule
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int insert(DutySchedule row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dutyschedule
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int insertSelective(DutySchedule row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dutyschedule
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	List<DutySchedule> selectByExample(DutyScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dutyschedule
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	DutySchedule selectByPrimaryKey(Integer dutyscheduleid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dutyschedule
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") DutySchedule row, @Param("example") DutyScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dutyschedule
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int updateByExample(@Param("row") DutySchedule row, @Param("example") DutyScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dutyschedule
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int updateByPrimaryKeySelective(DutySchedule row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dutyschedule
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int updateByPrimaryKey(DutySchedule row);
}
