package com.Trang.webyte.mapper;

import com.Trang.webyte.model.Medicine;
import com.Trang.webyte.model.MedicineExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface MedicineMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medicine
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	long countByExample(MedicineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medicine
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	int deleteByExample(MedicineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medicine
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	int deleteByPrimaryKey(Integer medicineid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medicine
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	int insert(Medicine row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medicine
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	int insertSelective(Medicine row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medicine
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	List<Medicine> selectByExample(MedicineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medicine
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	Medicine selectByPrimaryKey(Integer medicineid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medicine
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Medicine row, @Param("example") MedicineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medicine
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	int updateByExample(@Param("row") Medicine row, @Param("example") MedicineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medicine
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	int updateByPrimaryKeySelective(Medicine row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medicine
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	int updateByPrimaryKey(Medicine row);
}