package com.Trang.webyte.mapper;

import com.Trang.webyte.model.Medicine;
import com.Trang.webyte.model.MedicineExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface MedicineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Mon Apr 04 14:21:11 ICT 2022
     */
    long countByExample(MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Mon Apr 04 14:21:11 ICT 2022
     */
    int deleteByExample(MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Mon Apr 04 14:21:11 ICT 2022
     */
    int deleteByPrimaryKey(Integer medicineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Mon Apr 04 14:21:11 ICT 2022
     */
    int insert(Medicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Mon Apr 04 14:21:11 ICT 2022
     */
    int insertSelective(Medicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Mon Apr 04 14:21:11 ICT 2022
     */
    List<Medicine> selectByExample(MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Mon Apr 04 14:21:11 ICT 2022
     */
    Medicine selectByPrimaryKey(Integer medicineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Mon Apr 04 14:21:11 ICT 2022
     */
    int updateByExampleSelective(@Param("record") Medicine record, @Param("example") MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Mon Apr 04 14:21:11 ICT 2022
     */
    int updateByExample(@Param("record") Medicine record, @Param("example") MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Mon Apr 04 14:21:11 ICT 2022
     */
    int updateByPrimaryKeySelective(Medicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Mon Apr 04 14:21:11 ICT 2022
     */
    int updateByPrimaryKey(Medicine record);
}