package com.Trang.webyte.mapper;

import com.Trang.webyte.model.Medical_bills;
import com.Trang.webyte.model.Medical_billsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface Medical_billsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medical_bills
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	long countByExample(Medical_billsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medical_bills
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	int deleteByExample(Medical_billsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medical_bills
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	int deleteByPrimaryKey(Integer medicalBillsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medical_bills
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	int insert(Medical_bills row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medical_bills
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	int insertSelective(Medical_bills row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medical_bills
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	List<Medical_bills> selectByExample(Medical_billsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medical_bills
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	Medical_bills selectByPrimaryKey(Integer medicalBillsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medical_bills
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Medical_bills row, @Param("example") Medical_billsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medical_bills
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	int updateByExample(@Param("row") Medical_bills row, @Param("example") Medical_billsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medical_bills
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	int updateByPrimaryKeySelective(Medical_bills row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table medical_bills
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	int updateByPrimaryKey(Medical_bills row);
}
