package com.Trang.webyte.mapper;

import com.Trang.webyte.model.News;
import com.Trang.webyte.model.NewsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface NewsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	long countByExample(NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int deleteByExample(NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int deleteByPrimaryKey(Integer newsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int insert(News record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int insertSelective(News record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	List<News> selectByExample(NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	News selectByPrimaryKey(Integer newsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") News row, @Param("example") NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int updateByExample(@Param("row") News row, @Param("example") NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByPrimaryKeySelective(News row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	int updateByPrimaryKey(News row);

	News selectbyid(int newsid);
}
