package com.Trang.webyte.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import com.Trang.webyte.model.PriceOfMedicalExaminationService;
import com.Trang.webyte.model.PriceOfMedicalExaminationServiceExample;

@Mapper
public interface PriceOfMedicalExaminationServiceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table price_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	long countByExample(PriceOfMedicalExaminationServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table price_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int deleteByExample(PriceOfMedicalExaminationServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table price_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int deleteByPrimaryKey(Integer idpriceOfMedicalExaminationService);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table price_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int insert(PriceOfMedicalExaminationService record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table price_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int insertSelective(PriceOfMedicalExaminationService record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table price_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	List<PriceOfMedicalExaminationService> selectByExample(PriceOfMedicalExaminationServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table price_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	PriceOfMedicalExaminationService selectByPrimaryKey(Integer idpriceOfMedicalExaminationService);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table price_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByExampleSelective(@Param("record") PriceOfMedicalExaminationService record,
			@Param("example") PriceOfMedicalExaminationServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table price_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByExample(@Param("record") PriceOfMedicalExaminationService record,
			@Param("example") PriceOfMedicalExaminationServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table price_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByPrimaryKeySelective(PriceOfMedicalExaminationService record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table price_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	int updateByPrimaryKey(PriceOfMedicalExaminationService record);
}
