package com.Trang.webyte.mapper;

import com.Trang.webyte.model.Price_Of_Medical_Examination_Service;
import com.Trang.webyte.model.Price_Of_Medical_Examination_ServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Price_Of_Medical_Examination_ServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    long countByExample(Price_Of_Medical_Examination_ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    int deleteByExample(Price_Of_Medical_Examination_ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    int deleteByPrimaryKey(Integer idpriceOfMedicalExaminationService);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    int insert(Price_Of_Medical_Examination_Service row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    int insertSelective(Price_Of_Medical_Examination_Service row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    List<Price_Of_Medical_Examination_Service> selectByExample(Price_Of_Medical_Examination_ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    Price_Of_Medical_Examination_Service selectByPrimaryKey(Integer idpriceOfMedicalExaminationService);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    int updateByExampleSelective(@Param("row") Price_Of_Medical_Examination_Service row, @Param("example") Price_Of_Medical_Examination_ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    int updateByExample(@Param("row") Price_Of_Medical_Examination_Service row, @Param("example") Price_Of_Medical_Examination_ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    int updateByPrimaryKeySelective(Price_Of_Medical_Examination_Service row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    int updateByPrimaryKey(Price_Of_Medical_Examination_Service row);
}
