package com.Trang.webyte.mapper;

import com.Trang.webyte.model.Symptom;
import com.Trang.webyte.model.SymptomExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SymptomMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symptom
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	long countByExample(SymptomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symptom
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int deleteByExample(SymptomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symptom
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int deleteByPrimaryKey(Integer idsymptom);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symptom
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int insert(Symptom row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symptom
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int insertSelective(Symptom row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symptom
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	List<Symptom> selectByExample(SymptomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symptom
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	Symptom selectByPrimaryKey(Integer idsymptom);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symptom
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Symptom row, @Param("example") SymptomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symptom
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int updateByExample(@Param("row") Symptom row, @Param("example") SymptomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symptom
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int updateByPrimaryKeySelective(Symptom row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table symptom
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	int updateByPrimaryKey(Symptom row);
}