package com.Trang.webyte.mapper;

import com.Trang.webyte.model.Type_Sick_DetailExample;
import com.Trang.webyte.model.Type_Sick_DetailKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Type_Sick_DetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    long countByExample(Type_Sick_DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    int deleteByExample(Type_Sick_DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    int deleteByPrimaryKey(Type_Sick_DetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    int insert(Type_Sick_DetailKey row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    int insertSelective(Type_Sick_DetailKey row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    List<Type_Sick_DetailKey> selectByExample(Type_Sick_DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    int updateByExampleSelective(@Param("row") Type_Sick_DetailKey row, @Param("example") Type_Sick_DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    int updateByExample(@Param("row") Type_Sick_DetailKey row, @Param("example") Type_Sick_DetailExample example);
}