package com.Trang.webyte.mapper;

import com.Trang.webyte.model.Type_Sick;
import com.Trang.webyte.model.Type_SickExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface Type_SickMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table typesick
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	long countByExample(Type_SickExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table typesick
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	int deleteByExample(Type_SickExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table typesick
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	int deleteByPrimaryKey(Integer idtypesick);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table typesick
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	int insert(Type_Sick record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table typesick
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	int insertSelective(Type_Sick record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table typesick
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	List<Type_Sick> selectByExample(Type_SickExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table typesick
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	Type_Sick selectByPrimaryKey(Integer idtypesick);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table typesick
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	int updateByExampleSelective(@Param("record") Type_Sick record, @Param("example") Type_SickExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table typesick
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	int updateByExample(@Param("record") Type_Sick record, @Param("example") Type_SickExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table typesick
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	int updateByPrimaryKeySelective(Type_Sick record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table typesick
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	int updateByPrimaryKey(Type_Sick record);
}