package com.Trang.webyte.model;

public class AccountKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.id
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.username
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	private String username;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.id
	 * @return  the value of account.id
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.id
	 * @param id  the value for account.id
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.username
	 * @return  the value of account.username
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.username
	 * @param username  the value for account.username
	 * @mbg.generated  Tue May 24 09:26:52 ICT 2022
	 */
	public void setUsername(String username) {
		this.username = username;
	}

}