package com.Trang.webyte.model;

import java.util.Date;

public class Appointment_Schedule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appointment_schedule.idappointment_schedule
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	private Integer idappointmentSchedule;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appointment_schedule.doctorid
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	private Integer doctorid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appointment_schedule.patientid
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	private Integer patientid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appointment_schedule.date
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appointment_schedule.status
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appointment_schedule.number
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	private Integer number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appointment_schedule.time
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	private String time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appointment_schedule.idappointment_schedule
	 * @return  the value of appointment_schedule.idappointment_schedule
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public Integer getIdappointmentSchedule() {
		return idappointmentSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appointment_schedule.idappointment_schedule
	 * @param idappointmentSchedule  the value for appointment_schedule.idappointment_schedule
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public void setIdappointmentSchedule(Integer idappointmentSchedule) {
		this.idappointmentSchedule = idappointmentSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appointment_schedule.doctorid
	 * @return  the value of appointment_schedule.doctorid
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public Integer getDoctorid() {
		return doctorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appointment_schedule.doctorid
	 * @param doctorid  the value for appointment_schedule.doctorid
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public void setDoctorid(Integer doctorid) {
		this.doctorid = doctorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appointment_schedule.patientid
	 * @return  the value of appointment_schedule.patientid
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public Integer getPatientid() {
		return patientid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appointment_schedule.patientid
	 * @param patientid  the value for appointment_schedule.patientid
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public void setPatientid(Integer patientid) {
		this.patientid = patientid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appointment_schedule.date
	 * @return  the value of appointment_schedule.date
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appointment_schedule.date
	 * @param date  the value for appointment_schedule.date
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appointment_schedule.status
	 * @return  the value of appointment_schedule.status
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appointment_schedule.status
	 * @param status  the value for appointment_schedule.status
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appointment_schedule.number
	 * @return  the value of appointment_schedule.number
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public Integer getNumber() {
		return number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appointment_schedule.number
	 * @param number  the value for appointment_schedule.number
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public void setNumber(Integer number) {
		this.number = number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appointment_schedule.time
	 * @return  the value of appointment_schedule.time
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appointment_schedule.time
	 * @param time  the value for appointment_schedule.time
	 * @mbg.generated  Wed May 25 09:13:05 ICT 2022
	 */
	public void setTime(String time) {
		this.time = time;
	}
}