package com.Trang.webyte.model;

import java.util.Date;

public class Doctor {

	private Integer doctorid;

	private String fullname;

	private String address;

	private String phone;

	private String email;

	private Integer accountid;

	private Integer deptid;

	private Date birthday;

	private String img;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.doctorid
	 * @return  the value of doctor.doctorid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public Integer getDoctorid() {
		return doctorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.doctorid
	 * @param doctorid  the value for doctor.doctorid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public void setDoctorid(Integer doctorid) {
		this.doctorid = doctorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.fullname
	 * @return  the value of doctor.fullname
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.fullname
	 * @param fullname  the value for doctor.fullname
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.address
	 * @return  the value of doctor.address
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.address
	 * @param address  the value for doctor.address
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.phone
	 * @return  the value of doctor.phone
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.phone
	 * @param phone  the value for doctor.phone
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.email
	 * @return  the value of doctor.email
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.email
	 * @param email  the value for doctor.email
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.accountid
	 * @return  the value of doctor.accountid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public Integer getAccountid() {
		return accountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.accountid
	 * @param accountid  the value for doctor.accountid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public void setAccountid(Integer accountid) {
		this.accountid = accountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.deptid
	 * @return  the value of doctor.deptid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public Integer getDeptid() {
		return deptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.deptid
	 * @param deptid  the value for doctor.deptid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.birthday
	 * @return  the value of doctor.birthday
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.birthday
	 * @param birthday  the value for doctor.birthday
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.img
	 * @return  the value of doctor.img
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.img
	 * @param img  the value for doctor.img
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public void setImg(String img) {
		this.img = img;
	}
}
