package com.Trang.webyte.model;

import com.Trang.webyte.DTO.DoctorDTO;

import java.util.Date;

public class Doctor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.doctorid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private Integer doctorid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.fullname
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.address
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.phone
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.email
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.accountid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private Integer accountid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.deptid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private Integer deptid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.birthday
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.img
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private String img;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.doctorid
	 * @return  the value of doctor.doctorid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public Integer getDoctorid() {
		return doctorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.doctorid
	 * @param doctorid  the value for doctor.doctorid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setDoctorid(Integer doctorid) {
		this.doctorid = doctorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.fullname
	 * @return  the value of doctor.fullname
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.fullname
	 * @param fullname  the value for doctor.fullname
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.address
	 * @return  the value of doctor.address
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.address
	 * @param address  the value for doctor.address
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.phone
	 * @return  the value of doctor.phone
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.phone
	 * @param phone  the value for doctor.phone
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.email
	 * @return  the value of doctor.email
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.email
	 * @param email  the value for doctor.email
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.accountid
	 * @return  the value of doctor.accountid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public Integer getAccountid() {
		return accountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.accountid
	 * @param accountid  the value for doctor.accountid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setAccountid(Integer accountid) {
		this.accountid = accountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.deptid
	 * @return  the value of doctor.deptid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public Integer getDeptid() {
		return deptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.deptid
	 * @param deptid  the value for doctor.deptid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.birthday
	 * @return  the value of doctor.birthday
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.birthday
	 * @param birthday  the value for doctor.birthday
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.img
	 * @return  the value of doctor.img
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.img
	 * @param img  the value for doctor.img
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setImg(String img) {
		this.img = img;
	}

	public Doctor(DoctorDTO doctorDTO, String img) {
		this.doctorid = doctorDTO.getDoctorid();
		this.fullname = doctorDTO.getFullname();
		this.address = doctorDTO.getAddress();
		this.phone = doctorDTO.getPhone();
		this.email = doctorDTO.getEmail();
		this.accountid = doctorDTO.getAccountid();
		this.birthday = doctorDTO.getBirthday();
		this.img = img;
	}

	public Doctor() {
	}
}
