package com.Trang.webyte.model;

public class Healthrecords {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column healthrecords.healthrecordsid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	private Integer healthrecordsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column healthrecords.prescriptionid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	private Integer prescriptionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column healthrecords.appointscheduleid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	private Integer appointscheduleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column healthrecords.healthrecordsid
	 * @return  the value of healthrecords.healthrecordsid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public Integer getHealthrecordsid() {
		return healthrecordsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column healthrecords.healthrecordsid
	 * @param healthrecordsid  the value for healthrecords.healthrecordsid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public void setHealthrecordsid(Integer healthrecordsid) {
		this.healthrecordsid = healthrecordsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column healthrecords.prescriptionid
	 * @return  the value of healthrecords.prescriptionid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public Integer getPrescriptionid() {
		return prescriptionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column healthrecords.prescriptionid
	 * @param prescriptionid  the value for healthrecords.prescriptionid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public void setPrescriptionid(Integer prescriptionid) {
		this.prescriptionid = prescriptionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column healthrecords.appointscheduleid
	 * @return  the value of healthrecords.appointscheduleid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public Integer getAppointscheduleid() {
		return appointscheduleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column healthrecords.appointscheduleid
	 * @param appointscheduleid  the value for healthrecords.appointscheduleid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public void setAppointscheduleid(Integer appointscheduleid) {
		this.appointscheduleid = appointscheduleid;
	}
}