package com.Trang.webyte.model;

public class Healthrecords {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column healthrecords.healthrecordsid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	private Integer healthrecordsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column healthrecords.prescriptionid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	private Integer prescriptionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column healthrecords.appointmentscheduleid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	private Integer appointmentscheduleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column healthrecords.healthrecordsid
	 * @return  the value of healthrecords.healthrecordsid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public Integer getHealthrecordsid() {
		return healthrecordsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column healthrecords.healthrecordsid
	 * @param healthrecordsid  the value for healthrecords.healthrecordsid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public void setHealthrecordsid(Integer healthrecordsid) {
		this.healthrecordsid = healthrecordsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column healthrecords.prescriptionid
	 * @return  the value of healthrecords.prescriptionid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public Integer getPrescriptionid() {
		return prescriptionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column healthrecords.prescriptionid
	 * @param prescriptionid  the value for healthrecords.prescriptionid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public void setPrescriptionid(Integer prescriptionid) {
		this.prescriptionid = prescriptionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column healthrecords.appointmentscheduleid
	 * @return  the value of healthrecords.appointmentscheduleid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public Integer getAppointmentscheduleid() {
		return appointmentscheduleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column healthrecords.appointmentscheduleid
	 * @param appointmentscheduleid  the value for healthrecords.appointmentscheduleid
	 * @mbg.generated  Mon May 30 17:00:26 ICT 2022
	 */
	public void setAppointmentscheduleid(Integer appointmentscheduleid) {
		this.appointmentscheduleid = appointmentscheduleid;
	}
}