package com.Trang.webyte.model;

import java.util.ArrayList;
import java.util.List;

public class Medical_billsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    public Medical_billsExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMedicalBillsidIsNull() {
            addCriterion("medical_billsid is null");
            return (Criteria) this;
        }

        public Criteria andMedicalBillsidIsNotNull() {
            addCriterion("medical_billsid is not null");
            return (Criteria) this;
        }

        public Criteria andMedicalBillsidEqualTo(Integer value) {
            addCriterion("medical_billsid =", value, "medicalBillsid");
            return (Criteria) this;
        }

        public Criteria andMedicalBillsidNotEqualTo(Integer value) {
            addCriterion("medical_billsid <>", value, "medicalBillsid");
            return (Criteria) this;
        }

        public Criteria andMedicalBillsidGreaterThan(Integer value) {
            addCriterion("medical_billsid >", value, "medicalBillsid");
            return (Criteria) this;
        }

        public Criteria andMedicalBillsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("medical_billsid >=", value, "medicalBillsid");
            return (Criteria) this;
        }

        public Criteria andMedicalBillsidLessThan(Integer value) {
            addCriterion("medical_billsid <", value, "medicalBillsid");
            return (Criteria) this;
        }

        public Criteria andMedicalBillsidLessThanOrEqualTo(Integer value) {
            addCriterion("medical_billsid <=", value, "medicalBillsid");
            return (Criteria) this;
        }

        public Criteria andMedicalBillsidIn(List<Integer> values) {
            addCriterion("medical_billsid in", values, "medicalBillsid");
            return (Criteria) this;
        }

        public Criteria andMedicalBillsidNotIn(List<Integer> values) {
            addCriterion("medical_billsid not in", values, "medicalBillsid");
            return (Criteria) this;
        }

        public Criteria andMedicalBillsidBetween(Integer value1, Integer value2) {
            addCriterion("medical_billsid between", value1, value2, "medicalBillsid");
            return (Criteria) this;
        }

        public Criteria andMedicalBillsidNotBetween(Integer value1, Integer value2) {
            addCriterion("medical_billsid not between", value1, value2, "medicalBillsid");
            return (Criteria) this;
        }

        public Criteria andDutyscheduleidIsNull() {
            addCriterion("dutyscheduleid is null");
            return (Criteria) this;
        }

        public Criteria andDutyscheduleidIsNotNull() {
            addCriterion("dutyscheduleid is not null");
            return (Criteria) this;
        }

        public Criteria andDutyscheduleidEqualTo(Integer value) {
            addCriterion("dutyscheduleid =", value, "dutyscheduleid");
            return (Criteria) this;
        }

        public Criteria andDutyscheduleidNotEqualTo(Integer value) {
            addCriterion("dutyscheduleid <>", value, "dutyscheduleid");
            return (Criteria) this;
        }

        public Criteria andDutyscheduleidGreaterThan(Integer value) {
            addCriterion("dutyscheduleid >", value, "dutyscheduleid");
            return (Criteria) this;
        }

        public Criteria andDutyscheduleidGreaterThanOrEqualTo(Integer value) {
            addCriterion("dutyscheduleid >=", value, "dutyscheduleid");
            return (Criteria) this;
        }

        public Criteria andDutyscheduleidLessThan(Integer value) {
            addCriterion("dutyscheduleid <", value, "dutyscheduleid");
            return (Criteria) this;
        }

        public Criteria andDutyscheduleidLessThanOrEqualTo(Integer value) {
            addCriterion("dutyscheduleid <=", value, "dutyscheduleid");
            return (Criteria) this;
        }

        public Criteria andDutyscheduleidIn(List<Integer> values) {
            addCriterion("dutyscheduleid in", values, "dutyscheduleid");
            return (Criteria) this;
        }

        public Criteria andDutyscheduleidNotIn(List<Integer> values) {
            addCriterion("dutyscheduleid not in", values, "dutyscheduleid");
            return (Criteria) this;
        }

        public Criteria andDutyscheduleidBetween(Integer value1, Integer value2) {
            addCriterion("dutyscheduleid between", value1, value2, "dutyscheduleid");
            return (Criteria) this;
        }

        public Criteria andDutyscheduleidNotBetween(Integer value1, Integer value2) {
            addCriterion("dutyscheduleid not between", value1, value2, "dutyscheduleid");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table medical_bills
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 17 22:19:08 ICT 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table medical_bills
     *
     * @mbg.generated Fri Jun 17 22:19:08 ICT 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}