package com.Trang.webyte.model;

public class Medicine {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medicine.medicineid
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	private Integer medicineid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medicine.medicinename
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	private String medicinename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medicine.status
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medicine.count
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	private Integer count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medicine.pack
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	private String pack;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medicine.medicineid
	 * @return  the value of medicine.medicineid
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public Integer getMedicineid() {
		return medicineid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medicine.medicineid
	 * @param medicineid  the value for medicine.medicineid
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public void setMedicineid(Integer medicineid) {
		this.medicineid = medicineid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medicine.medicinename
	 * @return  the value of medicine.medicinename
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public String getMedicinename() {
		return medicinename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medicine.medicinename
	 * @param medicinename  the value for medicine.medicinename
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public void setMedicinename(String medicinename) {
		this.medicinename = medicinename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medicine.status
	 * @return  the value of medicine.status
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medicine.status
	 * @param status  the value for medicine.status
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medicine.count
	 * @return  the value of medicine.count
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medicine.count
	 * @param count  the value for medicine.count
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medicine.pack
	 * @return  the value of medicine.pack
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public String getPack() {
		return pack;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medicine.pack
	 * @param pack  the value for medicine.pack
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public void setPack(String pack) {
		this.pack = pack;
	}
}