package com.Trang.webyte.model;

public class Medical_bills {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medical_bills.medical_billsid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	private Integer medicalBillsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medical_bills.appointscheduleid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	private Integer appointscheduleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medical_bills.price
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medical_bills.status
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medical_bills.medical_billsid
	 * @return  the value of medical_bills.medical_billsid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public Integer getMedicalBillsid() {
		return medicalBillsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medical_bills.medical_billsid
	 * @param medicalBillsid  the value for medical_bills.medical_billsid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public void setMedicalBillsid(Integer medicalBillsid) {
		this.medicalBillsid = medicalBillsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medical_bills.appointscheduleid
	 * @return  the value of medical_bills.appointscheduleid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public Integer getAppointscheduleid() {
		return appointscheduleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medical_bills.appointscheduleid
	 * @param appointscheduleid  the value for medical_bills.appointscheduleid
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public void setAppointscheduleid(Integer appointscheduleid) {
		this.appointscheduleid = appointscheduleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medical_bills.price
	 * @return  the value of medical_bills.price
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medical_bills.price
	 * @param price  the value for medical_bills.price
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medical_bills.status
	 * @return  the value of medical_bills.status
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medical_bills.status
	 * @param status  the value for medical_bills.status
	 * @mbg.generated  Wed Jun 22 09:57:43 ICT 2022
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}
