package com.Trang.webyte.model;

public class Prescription_Detail extends Prescription_DetailKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column prescription_detail.amount
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	private Integer amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column prescription_detail.dosage
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	private Integer dosage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column prescription_detail.duration
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	private String duration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column prescription_detail.times
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	private Integer times;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prescription_detail.amount
	 * @return  the value of prescription_detail.amount
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	public Integer getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prescription_detail.amount
	 * @param amount  the value for prescription_detail.amount
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prescription_detail.dosage
	 * @return  the value of prescription_detail.dosage
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	public Integer getDosage() {
		return dosage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prescription_detail.dosage
	 * @param dosage  the value for prescription_detail.dosage
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	public void setDosage(Integer dosage) {
		this.dosage = dosage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prescription_detail.duration
	 * @return  the value of prescription_detail.duration
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	public String getDuration() {
		return duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prescription_detail.duration
	 * @param duration  the value for prescription_detail.duration
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	public void setDuration(String duration) {
		this.duration = duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column prescription_detail.times
	 * @return  the value of prescription_detail.times
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	public Integer getTimes() {
		return times;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column prescription_detail.times
	 * @param times  the value for prescription_detail.times
	 * @mbg.generated  Tue Apr 12 14:42:06 ICT 2022
	 */
	public void setTimes(Integer times) {
		this.times = times;
	}
}