package com.Trang.webyte.model;

public class Price_Of_Medical_Examination_Service {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price _of_medical_examination_service.idprice _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    private Integer idpriceOfMedicalExaminationService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price _of_medical_examination_service.price
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price _of_medical_examination_service.derpamentid
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    private Integer derpamentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price _of_medical_examination_service.idprice _of_medical_examination_service
     *
     * @return the value of price _of_medical_examination_service.idprice _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    public Integer getIdpriceOfMedicalExaminationService() {
        return idpriceOfMedicalExaminationService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price _of_medical_examination_service.idprice _of_medical_examination_service
     *
     * @param idpriceOfMedicalExaminationService the value for price _of_medical_examination_service.idprice _of_medical_examination_service
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    public void setIdpriceOfMedicalExaminationService(Integer idpriceOfMedicalExaminationService) {
        this.idpriceOfMedicalExaminationService = idpriceOfMedicalExaminationService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price _of_medical_examination_service.price
     *
     * @return the value of price _of_medical_examination_service.price
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price _of_medical_examination_service.price
     *
     * @param price the value for price _of_medical_examination_service.price
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price _of_medical_examination_service.derpamentid
     *
     * @return the value of price _of_medical_examination_service.derpamentid
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    public Integer getDerpamentid() {
        return derpamentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price _of_medical_examination_service.derpamentid
     *
     * @param derpamentid the value for price _of_medical_examination_service.derpamentid
     *
     * @mbg.generated Tue May 24 09:26:52 ICT 2022
     */
    public void setDerpamentid(Integer derpamentid) {
        this.derpamentid = derpamentid;
    }
}
