package com.Trang.webyte.model;

public class PriceOfMedicalExaminationService {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column price_of_medical_examination_service.idprice_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private Integer idpriceOfMedicalExaminationService;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column price_of_medical_examination_service.price
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column price_of_medical_examination_service.doctortid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private Integer doctortid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column price_of_medical_examination_service.idprice_of_medical_examination_service
	 * @return  the value of price_of_medical_examination_service.idprice_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public Integer getIdpriceOfMedicalExaminationService() {
		return idpriceOfMedicalExaminationService;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column price_of_medical_examination_service.idprice_of_medical_examination_service
	 * @param idpriceOfMedicalExaminationService  the value for price_of_medical_examination_service.idprice_of_medical_examination_service
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setIdpriceOfMedicalExaminationService(Integer idpriceOfMedicalExaminationService) {
		this.idpriceOfMedicalExaminationService = idpriceOfMedicalExaminationService;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column price_of_medical_examination_service.price
	 * @return  the value of price_of_medical_examination_service.price
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column price_of_medical_examination_service.price
	 * @param price  the value for price_of_medical_examination_service.price
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column price_of_medical_examination_service.doctortid
	 * @return  the value of price_of_medical_examination_service.doctortid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public Integer getDoctortid() {
		return doctortid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column price_of_medical_examination_service.doctortid
	 * @param doctortid  the value for price_of_medical_examination_service.doctortid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setDoctortid(Integer doctortid) {
		this.doctortid = doctortid;
	}
}