package com.Trang.webyte.model;

public class Question {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column question.questionid
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	private Integer questionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column question.questioncontent
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	private String questioncontent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column question.topicid
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	private Integer topicid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column question.accountid
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	private Integer accountid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question.questionid
	 * @return  the value of question.questionid
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	public Integer getQuestionid() {
		return questionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question.questionid
	 * @param questionid  the value for question.questionid
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	public void setQuestionid(Integer questionid) {
		this.questionid = questionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question.questioncontent
	 * @return  the value of question.questioncontent
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	public String getQuestioncontent() {
		return questioncontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question.questioncontent
	 * @param questioncontent  the value for question.questioncontent
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	public void setQuestioncontent(String questioncontent) {
		this.questioncontent = questioncontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question.topicid
	 * @return  the value of question.topicid
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	public Integer getTopicid() {
		return topicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question.topicid
	 * @param topicid  the value for question.topicid
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	public void setTopicid(Integer topicid) {
		this.topicid = topicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question.accountid
	 * @return  the value of question.accountid
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	public Integer getAccountid() {
		return accountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question.accountid
	 * @param accountid  the value for question.accountid
	 * @mbg.generated  Tue May 31 14:47:12 ICT 2022
	 */
	public void setAccountid(Integer accountid) {
		this.accountid = accountid;
	}
}