package com.Trang.webyte.model;

public class Sick {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sick.sickid
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	private Integer sickid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sick.sickname
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	private String sickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sick.idsicktype
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	private Integer idsicktype;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sick.sickid
	 * @return  the value of sick.sickid
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	public Integer getSickid() {
		return sickid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sick.sickid
	 * @param sickid  the value for sick.sickid
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	public void setSickid(Integer sickid) {
		this.sickid = sickid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sick.sickname
	 * @return  the value of sick.sickname
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	public String getSickname() {
		return sickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sick.sickname
	 * @param sickname  the value for sick.sickname
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	public void setSickname(String sickname) {
		this.sickname = sickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sick.idsicktype
	 * @return  the value of sick.idsicktype
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	public Integer getIdsicktype() {
		return idsicktype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sick.idsicktype
	 * @param idsicktype  the value for sick.idsicktype
	 * @mbg.generated  Tue Jun 21 00:50:28 ICT 2022
	 */
	public void setIdsicktype(Integer idsicktype) {
		this.idsicktype = idsicktype;
	}
}