package com.Trang.webyte.model;

public class Topic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.topicid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private Integer topicid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.topicname
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private String topicname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.topiccontent
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	private String topiccontent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.topicid
	 * @return  the value of topic.topicid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public Integer getTopicid() {
		return topicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.topicid
	 * @param topicid  the value for topic.topicid
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setTopicid(Integer topicid) {
		this.topicid = topicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.topicname
	 * @return  the value of topic.topicname
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public String getTopicname() {
		return topicname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.topicname
	 * @param topicname  the value for topic.topicname
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setTopicname(String topicname) {
		this.topicname = topicname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.topiccontent
	 * @return  the value of topic.topiccontent
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public String getTopiccontent() {
		return topiccontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.topiccontent
	 * @param topiccontent  the value for topic.topiccontent
	 * @mbg.generated  Fri Jun 17 22:19:08 ICT 2022
	 */
	public void setTopiccontent(String topiccontent) {
		this.topiccontent = topiccontent;
	}
}