package com.Trang.webyte.model;

public class Type_Sick_DetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typesick_detail.symptomid
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    private Integer symptomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typesick_detail.sickid
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    private Integer sickid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typesick_detail.symptomid
     *
     * @return the value of typesick_detail.symptomid
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public Integer getSymptomid() {
        return symptomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typesick_detail.symptomid
     *
     * @param symptomid the value for typesick_detail.symptomid
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public void setSymptomid(Integer symptomid) {
        this.symptomid = symptomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typesick_detail.sickid
     *
     * @return the value of typesick_detail.sickid
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public Integer getSickid() {
        return sickid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typesick_detail.sickid
     *
     * @param sickid the value for typesick_detail.sickid
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public void setSickid(Integer sickid) {
        this.sickid = sickid;
    }
}