package com.Trang.webyte.model;

public class Type_Sick {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column typesick.idtypesick
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	private Integer idtypesick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column typesick.typesickname
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	private String typesickname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column typesick.idtypesick
	 * @return  the value of typesick.idtypesick
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	public Integer getIdtypesick() {
		return idtypesick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column typesick.idtypesick
	 * @param idtypesick  the value for typesick.idtypesick
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	public void setIdtypesick(Integer idtypesick) {
		this.idtypesick = idtypesick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column typesick.typesickname
	 * @return  the value of typesick.typesickname
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	public String getTypesickname() {
		return typesickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column typesick.typesickname
	 * @param typesickname  the value for typesick.typesickname
	 * @mbg.generated  Sat May 21 15:21:27 ICT 2022
	 */
	public void setTypesickname(String typesickname) {
		this.typesickname = typesickname;
	}
}