package com.Trang.webyte.model;

import java.util.ArrayList;
import java.util.List;

public class Type_Sick_DetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public Type_Sick_DetailExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSymptomidIsNull() {
            addCriterion("symptomid is null");
            return (Criteria) this;
        }

        public Criteria andSymptomidIsNotNull() {
            addCriterion("symptomid is not null");
            return (Criteria) this;
        }

        public Criteria andSymptomidEqualTo(Integer value) {
            addCriterion("symptomid =", value, "symptomid");
            return (Criteria) this;
        }

        public Criteria andSymptomidNotEqualTo(Integer value) {
            addCriterion("symptomid <>", value, "symptomid");
            return (Criteria) this;
        }

        public Criteria andSymptomidGreaterThan(Integer value) {
            addCriterion("symptomid >", value, "symptomid");
            return (Criteria) this;
        }

        public Criteria andSymptomidGreaterThanOrEqualTo(Integer value) {
            addCriterion("symptomid >=", value, "symptomid");
            return (Criteria) this;
        }

        public Criteria andSymptomidLessThan(Integer value) {
            addCriterion("symptomid <", value, "symptomid");
            return (Criteria) this;
        }

        public Criteria andSymptomidLessThanOrEqualTo(Integer value) {
            addCriterion("symptomid <=", value, "symptomid");
            return (Criteria) this;
        }

        public Criteria andSymptomidIn(List<Integer> values) {
            addCriterion("symptomid in", values, "symptomid");
            return (Criteria) this;
        }

        public Criteria andSymptomidNotIn(List<Integer> values) {
            addCriterion("symptomid not in", values, "symptomid");
            return (Criteria) this;
        }

        public Criteria andSymptomidBetween(Integer value1, Integer value2) {
            addCriterion("symptomid between", value1, value2, "symptomid");
            return (Criteria) this;
        }

        public Criteria andSymptomidNotBetween(Integer value1, Integer value2) {
            addCriterion("symptomid not between", value1, value2, "symptomid");
            return (Criteria) this;
        }

        public Criteria andSickidIsNull() {
            addCriterion("sickid is null");
            return (Criteria) this;
        }

        public Criteria andSickidIsNotNull() {
            addCriterion("sickid is not null");
            return (Criteria) this;
        }

        public Criteria andSickidEqualTo(Integer value) {
            addCriterion("sickid =", value, "sickid");
            return (Criteria) this;
        }

        public Criteria andSickidNotEqualTo(Integer value) {
            addCriterion("sickid <>", value, "sickid");
            return (Criteria) this;
        }

        public Criteria andSickidGreaterThan(Integer value) {
            addCriterion("sickid >", value, "sickid");
            return (Criteria) this;
        }

        public Criteria andSickidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sickid >=", value, "sickid");
            return (Criteria) this;
        }

        public Criteria andSickidLessThan(Integer value) {
            addCriterion("sickid <", value, "sickid");
            return (Criteria) this;
        }

        public Criteria andSickidLessThanOrEqualTo(Integer value) {
            addCriterion("sickid <=", value, "sickid");
            return (Criteria) this;
        }

        public Criteria andSickidIn(List<Integer> values) {
            addCriterion("sickid in", values, "sickid");
            return (Criteria) this;
        }

        public Criteria andSickidNotIn(List<Integer> values) {
            addCriterion("sickid not in", values, "sickid");
            return (Criteria) this;
        }

        public Criteria andSickidBetween(Integer value1, Integer value2) {
            addCriterion("sickid between", value1, value2, "sickid");
            return (Criteria) this;
        }

        public Criteria andSickidNotBetween(Integer value1, Integer value2) {
            addCriterion("sickid not between", value1, value2, "sickid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table typesick_detail
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 22 09:57:43 ICT 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table typesick_detail
     *
     * @mbg.generated Wed Jun 22 09:57:43 ICT 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}