package com.Trang.webyte.model;

public class Type_Of_Clinic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column typeofclinic.typeofclinicid
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	private Integer typeofclinicid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column typeofclinic.typeofclinicname
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	private String typeofclinicname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column typeofclinic.typeofclinicid
	 * @return  the value of typeofclinic.typeofclinicid
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public Integer getTypeofclinicid() {
		return typeofclinicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column typeofclinic.typeofclinicid
	 * @param typeofclinicid  the value for typeofclinic.typeofclinicid
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public void setTypeofclinicid(Integer typeofclinicid) {
		this.typeofclinicid = typeofclinicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column typeofclinic.typeofclinicname
	 * @return  the value of typeofclinic.typeofclinicname
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public String getTypeofclinicname() {
		return typeofclinicname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column typeofclinic.typeofclinicname
	 * @param typeofclinicname  the value for typeofclinic.typeofclinicname
	 * @mbg.generated  Thu Jun 02 12:01:52 ICT 2022
	 */
	public void setTypeofclinicname(String typeofclinicname) {
		this.typeofclinicname = typeofclinicname;
	}
}